services:
  ngcash_postgres_db:
    image: postgres
    container_name: ngcash_postgres_db
    restart: always
    ports:
      - 4455:5432
    env_file:
      - ./back-end/.env
    volumes:
      - ngcash_postgres_db:/var/lib/postgresql/data

  ngcash_app_node:
    build: ./back-end
    container_name: ngcash_app_node
    ports:
      - 5000:5000
    depends_on:
      - ngcash_postgres_db
    env_file:
      - ./back-end/.env

  ngcash_app_react:
    build: ./front-end
    container_name: ngcash_app_react
    depends_on:
      - ngcash_postgres_db
      - ngcash_app_node
    volumes:
      - build_react:/var/www/html
    env_file:
      - ./front-end/.env

  ngcash_nginx:
    build: ./nginx
    container_name: ngcash_nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - ngcash_app_react

volumes:
  ngcash_postgres_db:
  build_react:
